

# Dating Dataset Analysis

Dating has undergone major overhauls in the past decades, first with the introduction of online dating and again with the rise of dating apps. Apps such as Tinder, Bumble, Hinge, OKCupid, and more all have the same goal: to facilitate successful romantic connections. Success is a difficult metric to define in such a nebulous scenario, and some artificial metric must be imposed. For example, OKCupid has performed data analyses with success defined as a certain number of messages being exchanged back and forth between users.

A common method of "matching" with a potential date on these apps. In this scenario users swipe left to reject another user and right to accept. From here, people are able to message and interact. For heterosexual couples, apps like Bumble require the woman to first accept a message request from any male suitor. On Hinge, you don't swipe right, but rather send a "like" on some aspect of a potential date's profile.

Despite variation across different apps, these swipe-based dating platforms all share the same flow:
1. Users quickly evaluate each other.
1. Users make a fast decision on whether or not to open up discussion with each other.
1. Users proceed to talk and possibly go on an in-person date.

An old-school form of meeting people, the Speed Dating event, follows this same general format. Instead of performing evaluation based on a user-setup profile, users reach their decision in a short several-minute timespan talking with multiple potential matches. At the end of the event, matches can choose to exchange information (swiping left) or not (swiping right). In these cases, success can be defined as a follow-up date between two interested parties. 


### The Challenge 

Plenty of research has been done on studying online interactions between users to try and optimize successful romantic connections. However, in the post-coronavirus world, different forms of communicating have taken hold. It is now common for folks to have virtual happy hours, virtual watch parties, and even video dates. 

How can dating be revolutionized for a post-coronavirus society? I suggest we look back to the old school and ask what lessons we can learn from the speed dating event. When is a speed dating even successful, and what kind of personalities perform best at these events? How can these lessons be applied to swipe-based dating? Would a new service, such as virtual speed-dating, be a potential method for deeper emotional connections between users and successful matches?

### The Dataset

Colombia University professors Ray Fisman adn Sheena Iyengar [ran a series of speed dating experiments](http://www.stat.columbia.edu/~gelman/arm/examples/speed.dating/) on Columbia graduate students from 2002 to 2004, and have made this data public. They collected details before, during, and after the event, and followed up with participants to evaluate longer-term success rates. 

Twenty-one different speed dating events were held with a total of 552 different individuals attending. Before each event, demographic information such as the subject's field of study, undegraduate alma mater, SAT score, zip code of childhood home, where the subject is from, median household income, race, and gender were collected. A series of preferential questions were also asked:
1. How important is it to you (on a scale of 1-10) that a person you date be of the same racial/ethnic background?
1. How important is it to you (on a scale of 1-10) that a person you date be of the same religious background?

Next, questions regarding the expectations of the participants were asked. The details of these questions can be seen in the data key.

## Data Exploration

First let's do some exploratory analysis of the data. The first step is to load it up into a Pandas dataframe.

In [6]:
import pandas as pd

df = pd.read_csv("dating-data.csv", encoding='latin1')
df.head()

,iid,id,gender,idg,condtn,wave,round,position,position1,order,...,attr3_3,sinc3_3,intel3_3,fun3_3,amb3_3,attr5_3,sinc5_3,intel5_3,fun5_3,amb5_3
0,1,1.0,0,1,1,1,10,7,NaN,4,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
1,1,1.0,0,1,1,1,10,7,NaN,3,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
2,1,1.0,0,1,1,1,10,7,NaN,10,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
3,1,1.0,0,1,1,1,10,7,NaN,5,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
4,1,1.0,0,1,1,1,10,7,NaN,7,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN

The target variables in this data set is 


We have 195 attributes to start. Looking at the data key, we see that data includes information such as:
 * `iid`: Unique identifier for each separate subject.
 * `id`: Subject number within a speed dating event, or "wave".
 * `idg`: Subject number within their gender group. 
 
These are a lot of different IDs. In fact, we see later in